### ISSUE TITLE
Meeting - Time search input textbox does not function

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mRSS#67]
Screenshot Example

![time_input_search_can_not_input](https://user-images.githubusercontent.com/11938477/52729008-53d37180-2f86-11e9-992c-8dc051a514f2.jpg)

**Comment by bluenevus** [comment]
We don't want this to work because the keyboard will block the touch input so please close

On Feb 13, 2019 10:56 AM, LAlexMHllc <notifications@github.com> wrote:

Screenshot Example

[time_input_search_can_not_input]<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F11938477%2F52729008-53d37180-2f86-11e9-992c-8dc051a514f2.jpg&data=02%7C01%7Cfrank.tucker%40microhealthllc.com%7Cb20c2e97ea4c4e4be8bb08d691d4271d%7C487ea2d67ea04a4b87736f4833ed2108%7C0%7C0%7C636856737766747352&sdata=hj9E5tBiWHH3TCAzbCrCWBwzLykykrS4IjZVqsawDWw%3D&reserved=0>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicroHealthLLC%2FmRSS%2Fissues%2F67&data=02%7C01%7Cfrank.tucker%40microhealthllc.com%7Cb20c2e97ea4c4e4be8bb08d691d4271d%7C487ea2d67ea04a4b87736f4833ed2108%7C0%7C0%7C636856737766747352&sdata=4ReCjZa8EJPh4515PZzsST9i4pk9RC3H3JGXdmwZjew%3D&reserved=0>, or mute the thread<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FADgTo3bdfrWLibtfld4rzi64Sdm_QjoBks5vNEOogaJpZM4a51yo&data=02%7C01%7Cfrank.tucker%40microhealthllc.com%7Cb20c2e97ea4c4e4be8bb08d691d4271d%7C487ea2d67ea04a4b87736f4833ed2108%7C0%7C0%7C636856737766757362&sdata=OW2KyQL2FjDPnHB61%2Fu7a0mdeXE84vZTj0ELTmOA7A4%3D&reserved=0>.

--- CONFIDENTIALITY NOTICE-If you are not the intended recipient you are notified that disclosing, copying, distributing or taking any action in reliance on the contents of this information is strictly prohibited. Please notify the sender immediately by e-mail and delete this e-mail from your system. Thank You.
